declare const chrome: any
declare const browser: any
declare const idbKeyval: any
declare const OmegaPac: any
declare const compareVersions: any
declare const JSZip: any
declare const saveAs: any
declare const drawOmega: any
declare const angular: any
declare const OmegaTargetChromium: any
declare const OmegaDebug: any
declare const OmegaTarget: any
